name: Deploy Solar Monitor

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: |
        cd server
        npm install
        
    - name: Run server
      run: |
        cd server
        nohup node server.js > server.log 2>&1 &
      continue-on-error: true